In [6]:
import pandas as pd

In [3]:
df = pd.read_csv('Titanic-Dataset.csv')

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df2 = pd.read_csv('insurance.csv')

In [8]:
df2.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

### Titanic Dataset

In [5]:
from ydata_profiling import ProfileReport
profile = ProfileReport(df)
profile.to_file(output_file='titanic_output.html')

Summarize dataset:  24%|████████▏                          | 4/17 [00:00<00:01,  8.44it/s, Describe variable: Embarked]
Summarize dataset:  59%|████████████████████              | 10/17 [00:00<00:00, 23.10it/s, Describe variable: Embarked]
100%|██████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 79.94it/s]
Summarize dataset: 100%|████████████████████████████████████████████████████| 47/47 [00:05<00:00,  8.15it/s, Completed]
Generate report structure: 100%|█████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.65s/it]
Render HTML: 100%|███████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.74s/it]
Export report to file: 100%|█████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 39.14it/s]

### Insurance dataset

In [9]:
from ydata_profiling import ProfileReport
profile = ProfileReport(df2)
profile.to_file(output_file='insurance_output.html')

Summarize dataset:  17%|██████                              | 2/12 [00:00<00:01,  5.91it/s, Describe variable: charges]
100%|████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 94.46it/s]
Summarize dataset: 100%|████████████████████████████████████████████████████| 32/32 [00:03<00:00,  8.01it/s, Completed]
Generate report structure: 100%|█████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.72s/it]
Render HTML: 100%|███████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.19it/s]
Export report to file: 100%|█████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 73.02it/s]